services:
  no-smoking-dbms:
    image: postgres:14
    container_name: no-smoking-dbms
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: no_smoking
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "port=5433", "-c", "listen_addresses=127.0.0.1" ]

volumes:
  db_data:
