#!/bin/bash
#
# Script is a wrapper which runs application in a bash script with the needed options
#
exec $SNAP/bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djava.desktop.appName=$SNAP/meta/gui/no-smoking.desktop -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3  -jar $SNAP/jar/nosmoking.jar "$@"