spring:
  application:
    name: no-smoking-java-desktop
  main:
    web-application-type: none
    com:
      andreidodu:
        no_smoking: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000