name: nosmoking
version: '1.0.0'
summary: No Smoking
description: |
  Helps to quit smoking.
grade: stable
confinement: strict
base: core24
icon: snap/gui/icon.png
title: No Smoking
website: https://andre-i.eu
issues: https://github.com/goto-eof
license: MIT
compression: xz
slots:
  no-smoking-dbus:
    interface: dbus
    bus: session
    name: it.es5.no-smoking.dbus
apps:
  no-smoking:
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP_DESKTOP_RUNTIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gio/modules
    command: executor
    extensions: [ gnome ]
    plugs:
      - network
      - x11
      - browser-support
      - unity7
      - home
      - desktop
      - desktop-legacy
      - removable-media
      - wayland
      - network-bind
    slots:
      - no-smoking-dbus
platforms:
  amd64:
    build-on: [ amd64 ]
    build-for: [ amd64 ]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]
parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local
  application:
    plugin: maven
    source: .
    build-packages:
      - on amd64: [ openjdk-11-jdk:amd64 ]
      - on arm64: [ openjdk-11-jdk:arm64 ]
      - maven
    stage-packages:
      - glib-networking
      - libgtk-3-0
      - xdg-utils
      - on amd64: [ openjdk-11-jre:amd64 ]
      - on arm64: [ openjdk-11-jre:arm64 ]
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*64/lib/security/blacklisted.certs

